---
name: "Gitea Auto-PR"
description: Create a new PR on Gitea.
inputs:
  url:
    description: URL to the Gitea instance
    required: true
  token:
    description: Personal access token to the Gitea instance
    required: true
  tea-version:
    description: Tea CLI version
    required: true
    default: 0.9.2
  pr-label:
    description: Issues label for the PR
  assignee:
    description: User to assign the PR to

branding:
  icon: git-pull-request
  color: green

runs:
  using: composite
  steps:
    - name: Check the OS of the runner
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1

    - name: Check architecture of the runner
      if: ${{ runner.arch != 'x64' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support x64 Architecture Only"
        exit 1

    - name: Get the commit message
      id: commit
      shell: bash
      run: |
        {
          echo "COMMIT_MSG<<EOF"
          git log -n 1 --format=%s
          echo EOF
        } >> "$GITHUB_OUTPUT"
        {
          echo "COMMIT_DESC<<EOF"
          git log -n 1 --format=%b
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Install Tea
      env:
        TEA_DL_URL: "https://dl.gitea.com/tea/${{ inputs.tea-version }}\
          /tea-${{ inputs.tea-version }}-linux-amd64"
      shell: bash
      run: |
        TEA_DIR=$(mktemp -d -t tmp.XXXX)
        pushd $TEA_DIR
        wget "$TEA_DL_URL"
        wget "${TEA_DL_URL}.sha256"
        if $(sha256sum --quiet -c "tea-${{ inputs.tea-version }}-linux-amd64.sha256"); then
          mv "tea-${{ inputs.tea-version }}-linux-amd64" /usr/bin/tea
          chmod +x /usr/bin/tea
          popd
          rm -rf $TEA_DIR
        else
          popd
          rm -rf $TEA_DIR
          echo "::error title=⛔ error hint::Tea v${{ inputs.tea-version }} Checksum Failed"
          exit 1
        fi

    - name: Login to Gitea
      shell: bash
      env:
        GIT_SERVER_URL: ${{ inputs.url }}
        GIT_SERVER_TOKEN: ${{ inputs.token }}
      run: >-
        tea login add
        -u "$GIT_SERVER_URL"
        -t "$GIT_SERVER_TOKEN"

    - name: Check for existing pull request
      id: no-pr
      continue-on-error: true
      shell: bash
      run: >-
        tea pr -f head -o simple |
        grep -q ${{ github.ref_name }} &&
        exit 1 ||
        exit 0

    - name: Create pull request
      if: steps.no-pr.outcome == 'success'
      env:
        COMMIT_MSG: ${{ steps.commit.outputs.COMMIT_MSG }}
        COMMIT_DESC: ${{ steps.commit.outputs.COMMIT_DESC }}
      shell: bash
      run: >-
        tea pr create -a "${{ inputs.assignee }}"
        -L "${{ inputs.pr-label }}"
        -t "$COMMIT_MSG"
        -d "$COMMIT_DESC"

    - name: Skip pull request
      if: steps.no-pr.outcome == 'failure'
      shell: bash
      run: >
          echo "::error title=⛔ error hint::
          A PR already exists for this branch: ${{ github.ref_name }}"
